version: '3.9'

services:
  dev:
    image: node:18.18.0
    volumes:
    - .:/ws
    entrypoint: bash -c "npm install && npm start -- --host=0.0.0.0 --disable-host-check; tail -f"
    working_dir: /ws/opinion-ate-2
    ports:
    - 14200:4200
