version: '3.9'

services:
  dev:
    image: node:18.18.0
    volumes:
    - .:/ws
    entrypoint: bash -c "npm install && npm start -- --host=0.0.0.0 --disable-host-check; tail -f"
    working_dir: /ws/opinion-ate-2
    ports:
    - 14200:4200

  e2e:
    image: mcr.microsoft.com/playwright:v1.39.0-jammy
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate-2
    entrypoint: bash -cx "npm install && npx playwright test; tail -f"
    links:
      - "dev:application"

  git:
    image: node:18.18.0-alpine
    volumes:
    - .:/ws
    - $HOME/.ssh:/root/.ssh
    - $HOME/.gitconfig:/root/.gitconfig
    working_dir: /ws
    entrypoint: sh -cx "apk upgrade && apk add git openssh-client; tail -f"

