name: ci
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      working-directory: ./opinion-ate-2
      run: npm ci
    - name: lint
      working-directory: ./opinion-ate-2
      run: npm run lint
    - name: unit tests
      working-directory: ./opinion-ate-2
      run: npm test
    - name: install playwright browsers
      working-directory: ./opinion-ate-2
      run: npx playwright install --with-deps
    - name: e2e tests
      working-directory: ./opinion-ate-2
      run: E2E_BASE_URL='http://localhost:4200' npm run ci:e2e

